[package]
name = "baz"
description = "baz — a fast, open-source music player for people who own their music"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
baz-core = { workspace = true }
dirs = { workspace = true }
iced = { workspace = true }
image = { workspace = true }
lofty = { workspace = true }
lru = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
hound = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
